name: Validacion de compilacion Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validacion:
    runs-on: ubuntu-latest

    steps:

      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir imagen con Docker Build
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: calculadora-python

      - name: Ejecutar Docker Bake
        uses: docker/bake-action@v6

      - name: Ejecutar contenedor Docker
        run: docker run calculadora-python